@startuml
class TimeSlot {
}
class "List`1"<T> {
}
BaseEntity <|-- TimeSlot
TimeSlot --> "TimeBegin" DateTime
TimeSlot --> "TimeEnd" DateTime
TimeSlot o-> "Doctors<Doctor>" "List`1"
TimeSlot o-> "Records<Record>" "List`1"
@enduml
