@startuml
class TimeSlot {
    + IsVacant : bool <<get>> <<set>>
}
class "List`1"<T> {
}
BaseEntity <|-- TimeSlot
TimeSlot --> "TimeBegin" DateTime
TimeSlot --> "TimeEnd" DateTime
TimeSlot o-> "Doctors<Doctor>" "List`1"
TimeSlot o-> "Record" Record
@enduml
