@startuml
class DoctorsController {
    + DoctorsController(doctorsService:IDoctorsService)
    + <<async>> GetAllDoctorsAsync() : Task<IActionResult>
    + <<async>> GetDoctorByIdAsync(id:int) : Task<IActionResult>
    + <<async>> CreateNewDoctorAsync(createDoctorDto:CreateDoctorDto) : Task<IActionResult>
    + <<async>> UpdateDoctorAsync(updateDoctorDto:UpdateDoctorDto) : Task<IActionResult>
    + <<async>> DeleteDoctorAsync(id:int) : Task<IActionResult>
}
ControllerBase <|-- DoctorsController
DoctorsController --> "_doctorsService" IDoctorsService
@enduml
