@startuml
interface ITimeSlotService {
    GetTimeSlotsBySpecificationsAsync(criteriaRequestDto:AvailableTimeSlotsByCriteriaRequestDto) : Task<IEnumerable<GetTimeSlotDto>>
    GetAllTimeSlotsAsync() : Task<IEnumerable<GetTimeSlotDto>>
    GetTimeSlotByIdAsync(id:int) : Task<GetTimeSlotDto>
    AddNewTimeSlotAsync(createTimeSlotDto:CreateTimeSlotDto) : Task<GetTimeSlotDto>
    UpdateTimeSlotAsync(updateTimeSlotDto:UpdateTimeSlotDto) : Task<GetTimeSlotDto>
    DeleteTimeSlotAsync(id:int) : Task<GetTimeSlotDto>
}
@enduml
