@startuml
class PatientService {
    + PatientService(patientRepository:IPatientRepository, mapper:IMapper)
    + <<async>> GetAllPatientsAsync() : Task<IEnumerable<GetPatientDto>>
    + <<async>> GetPatientByIdAsync(id:int) : Task<GetPatientDto>
    + <<async>> AddNewPatientAsync(createPatientDto:CreatePatientDto) : Task<GetPatientDto>
    + <<async>> UpdatePatientAsync(updatePatientDto:UpdatePatientDto) : Task<GetPatientDto>
    + <<async>> DeletePatientAsync(id:int) : Task<GetPatientDto>
}
IPatientService <|-- PatientService
PatientService --> "_patientRepository" IPatientRepository
PatientService --> "_mapper" IMapper
@enduml
