@startuml
class TimeSlotService {
    + TimeSlotService(patientService:IPatientService, timeSlotsRepository:ITimeSlotsRepository, doctorsService:IDoctorsService, mapper:IMapper)
    + <<async>> GetTimeSlotsBySpecificationsAsync(criteriaRequestDto:AvailableTimeSlotsByCriteriaRequestDto) : Task<IEnumerable<GetTimeSlotDto>>
    + <<async>> GetAllTimeSlotsAsync() : Task<IEnumerable<GetTimeSlotDto>>
    + <<async>> GetTimeSlotByIdAsync(id:int) : Task<GetTimeSlotDto>
    + <<async>> AddNewTimeSlotAsync(createTimeSlotDto:CreateTimeSlotDto) : Task<GetTimeSlotDto>
    + <<async>> UpdateTimeSlotAsync(updateTimeSlotDto:UpdateTimeSlotDto) : Task<GetTimeSlotDto>
    + <<async>> DeleteTimeSlotAsync(id:int) : Task<GetTimeSlotDto>
}
ITimeSlotService <|-- TimeSlotService
TimeSlotService --> "_patientService" IPatientService
TimeSlotService --> "_timeSlotsRepository" ITimeSlotsRepository
TimeSlotService --> "_doctorsService" IDoctorsService
TimeSlotService --> "_mapper" IMapper
@enduml
