@startuml
interface ITimeSlotsRepository {
    GetAvailableTimeSlotsByPredicateAsync(predicateBuilder:ExpressionStarter<TimeSlot>) : Task<IEnumerable<TimeSlot>>
}
class "IGenericRepository`1"<T> {
}
"IGenericRepository`1" "<TimeSlot>" <|-- ITimeSlotsRepository
@enduml
